server:
  port: 9999

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue2admin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://124.223.28.171:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: wulinxin
#    password: DDDNu555@
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
#    host: 124.223.28.171
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 50
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 3000
      # 连接池中的最大空闲连接
      max-idle: 20
      # 连接池中的最小空闲连接
      min-idle: 2
    # 连接池中的最小空闲连接
    timeout: 5000

    mvc:
      hiddenmethod:
        filter:
          enabled: true
config:

mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
zjj:
  jwt:
    header: Authorization
    expire: 604800 # 7天，秒单位
    secret: jsdjka87asdh1kcna2csaksmkua9sd8s

